name: Integration Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest commit message
        id: get_commit
        run: |
          echo "msg=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Run self-hosted commit message validation
        id: validator
        uses: ./
        with:
          commitMessage: "${{ steps.get_commit.outputs.msg }}"

      - name: Assert validation outcome
        run: |
          if [[ "${{ steps.validator.outputs.outcome }}" != "valid" ]]; then
            echo "Commit message does not follow required format (feat:, fix:, docs:)"
            exit 1
          else
            echo "Commit message is valid"
          fi
